# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38f2ddd22eb1e79da2e277fe57b1affcfc10f9000014047870991f88248e265895acf212f2b190ca6ea3c55af74a58291da66f139c40158cda6aa45a529c9f9b

test:
  secret_key_base: 1fe9094fc37977f28907ac64147aca5987b59d91605916faf4da991d2e9d1322e02ab4ae5eba8117c6ec2f7b3eef64faa3f755b4aa377c440756631c77199a69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
